export const UI_TEXT = {
  common: {
    loading: 'Carregando',
    error: 'Erro',
    search: 'Buscar',
    clear: 'Limpar',
    apply: 'Aplicar',
    close: 'Fechar',
    filters: 'Filtros',
    seeMore: 'Ver mais',
    back: 'Voltar',
  },
  details: {
    officialName: 'Nome oficial',
    capital: 'Capital',
    population: 'População',
    currency: 'Moeda',
    languages: 'Idiomas',
    region: 'Região',
    subregion: 'Sub-Região',
    flag: 'Bandeira',
  },
  continents: {
    title: 'Continentes',
    africa: 'África',
    northAmerica: 'América do Norte',
    centralAmerica: 'América Central',
    southAmerica: 'América do Sul',
    asia: 'Ásia',
    europe: 'Europa',
    oceania: 'Oceania',
    antarctic: 'Antártica',
  },
  filters: {
    searchPlaceholder: 'Informe o país que deseja conhecer...',
    selectLanguage: 'Selecione o idioma',
    noLanguageFound: 'Nenhum idioma encontrado',
    clearFilters: 'Limpar Filtros',
    applyFilters: 'Aplicar Filtros',
  },
  countries: {
    notFound: 'Nenhum país encontrado',
    adjustFilters: 'Ajuste os filtros para ver resultados',
    population: 'População',
    currency: 'Moeda',
    languages: 'Idiomas',
    region: 'Região',
    subregion: 'Sub-região',
    capital: 'Capital',
    area: 'Área',
    borders: 'Fronteiras',
    timezones: 'Fusos horários',
    independent: 'Independente',
    landlocked: 'Sem litoral',
    yes: 'Sim',
    no: 'Não',
  },
  pagination: {
    previousPage: 'Página anterior',
    nextPage: 'Próxima página',
    page: 'Página',
  },
  footer: {
    copyright: 'Grupo Plan Marketing © Todos os direitos reservados',
  },
  aria: {
    closeModal: 'Fechar modal',
    closeFilters: 'Fechar filtros',
    filterButton: 'Abrir filtros',
    logo: 'Logotipo Plan International',
    countryFlag: 'Bandeira de {country}',
    continentIcon: 'Ícone do continente',
  },
} as const

export const CONTINENT_NAMES: Record<string, string> = {
  Africa: UI_TEXT.continents.africa,
  Americas: 'Américas',
  'North America': UI_TEXT.continents.northAmerica,
  'Central America': UI_TEXT.continents.centralAmerica,
  'South America': UI_TEXT.continents.southAmerica,
  Asia: UI_TEXT.continents.asia,
  Europe: UI_TEXT.continents.europe,
  Oceania: UI_TEXT.continents.oceania,
  Antarctic: UI_TEXT.continents.antarctic,
}

export const CONTINENT_OPTIONS = [
  { value: 'Africa', label: UI_TEXT.continents.africa },
  { value: 'North America', label: UI_TEXT.continents.northAmerica },
  { value: 'Central America', label: UI_TEXT.continents.centralAmerica },
  { value: 'South America', label: UI_TEXT.continents.southAmerica },
  { value: 'Asia', label: UI_TEXT.continents.asia },
  { value: 'Europe', label: UI_TEXT.continents.europe },
  { value: 'Oceania', label: UI_TEXT.continents.oceania },
  { value: 'Antarctic', label: UI_TEXT.continents.antarctic },
] as const
